// This is file was generated by netdx on (2017-11-24 11:07:56 AM.
using System;
using Google.Protobuf;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
namespace Ndx.Decoders.Base
{
  public sealed partial class Frame
  {
    public static Frame DecodeJson(string jsonLine)
    {
      var jsonObject = JToken.Parse(jsonLine);
      return DecodeJson(jsonObject);
    }
    public static Frame DecodeJson(JToken token)
    {
      var obj = new Frame();
      {
        var val = token["frame_frame_encap_type"];
        if (val != null) { var propValue = val.Value<string>(); obj.FrameEncapType = Convert.ToInt32(propValue, 10); }
      }
      {
        var val = token["frame_frame_number"];
        if (val != null) { var propValue = val.Value<string>(); obj.FrameNumber = Convert.ToUInt32(propValue, 10); }
      }
      {
        var val = token["frame_frame_len"];
        if (val != null) { var propValue = val.Value<string>(); obj.FrameLen = Convert.ToUInt32(propValue, 10); }
      }
      {
        var val = token["frame_frame_cap_len"];
        if (val != null) { var propValue = val.Value<string>(); obj.FrameCapLen = Convert.ToUInt32(propValue, 10); }
      }
      {
        var val = token["frame_frame_protocols"];
        if (val != null) { var propValue = val.Value<string>(); obj.FrameProtocols = propValue; }
      }
      return obj;
    }
    public static Frame DecodeJson(JsonTextReader reader)                        
    {                                                                                     
        if (reader.TokenType != JsonToken.StartObject) return null;                       
        var obj = new Frame();                                                   
        reader.Read();                                                                    
        while (reader.TokenType != JsonToken.EndObject)                                   
        {                                                                                 
            if (reader.TokenType == JsonToken.PropertyName)                               
            {                                                                             
                string propName = (string)reader.Value;                                   
                reader.Read();                                                            
                if (reader.TokenType != JsonToken.String) { reader.Read(); continue; }    
                string propValue = (string)reader.Value;                                  
                SetField(obj, propName, propValue);                                       
            }                                                                             
            reader.Read();                                                                
        }                                                                                 
        reader.Read();                                                                    
        return obj;                                                                       
    }                                                                                     

    static void SetField(Frame obj, string propName, string propValue)           
    {                                                                                     
      switch (propName)                                                                   
      {                                                                                   
      case "frame_frame_encap_type": obj.FrameEncapType = Convert.ToInt32(propValue, 10); break;
      case "frame_frame_number": obj.FrameNumber = Convert.ToUInt32(propValue, 10); break;
      case "frame_frame_len": obj.FrameLen = Convert.ToUInt32(propValue, 10); break;
      case "frame_frame_cap_len": obj.FrameCapLen = Convert.ToUInt32(propValue, 10); break;
      case "frame_frame_protocols": obj.FrameProtocols = propValue; break;
      }
    }
    public static Google.Protobuf.ByteString StringToBytes(string str)        
    {                                                                         
      var bstrArr = str.Split(':');                                           
      var byteArray = new byte[bstrArr.Length];                               
      for (int i = 0; i < bstrArr.Length; i++)                                
      {                                                                       
        byteArray[i] = Convert.ToByte(bstrArr[i], 16);                        
      }                                                                       
      return Google.Protobuf.ByteString.CopyFrom( byteArray );                
    }                                                                         

  }
}
